name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at 00:00 UTC
  workflow_dispatch:     # Allows manual run from the Actions tab

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Contribution Grid
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./github-contribution-grid-snake.svg

      - name: Confirm SVG was generated
        run: ls -la

      - name: Push the SVG to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
